<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="samsung12.xsl"?>
<!DOCTYPE tariff [
<!ELEMENT tariff (category)+>
<!ELEMENT category (set, vodafone, ee, o2, three)>
<!ELEMENT set (#PCDATA)>
<!ELEMENT vodafone (#PCDATA)>
<!ELEMENT ee (#PCDATA)>
<!ELEMENT o2 (#PCDATA)>
<!ELEMENT three (#PCDATA)>
]>
<tariff>
	<category>
		<set>Monthly</set>
		<vodafone>£58.50</vodafone>
		<ee>£50.99</ee>
		<o2>£53.00</o2>
		<three>£50.00</three>
	</category>
	<category>
		<set>Handset</set>
		<vodafone>£199</vodafone>
		<ee>£9.99</ee>
		<o2>Free</o2>
		<three>Free</three>
	</category>
	<category>
		<set>Texts</set>
		<vodafone>Unlimited</vodafone>
		<ee>Unlimited</ee>
		<o2>Unlimited</o2>
		<three>Unlimited</three>
	</category>
	<category>
		<set>Minutes</set>
		<vodafone>Unlimited</vodafone>
		<ee>Unlimited</ee>
		<o2>Unlimited</o2>
		<three>Unlimited</three>
	</category>
	<category>
		<set>Data</set>
		<vodafone>7GB</vodafone>
		<ee>2GB</ee>
		<o2>5GB</o2>
		<three>Unlimited</three>
	</category>
</tariff>